### ISSUE TITLE
Flextesa equivalency

### ISSUE THREAD

**Issue by mweichert** [tez-capital/tezbox#5]
Hi there,

We maintain Taqueria, and currently use Flextesa for providing local sandbox functionality. I was stoked when I noticed your post on Tezos Agora Forum about TezBox.

We're exploring how to build a plugin for Taqueria that integrates with TezBox and have a couple of questions:

**How do we disable automatic baking?**
- In flextesa, we would set `--no-baking` when using the `mini-net` command.
- We would then manually bake blocks using: `octez-client bake for baker0`

**How do we set the block time?**:
- In flextesa, we would set `--time-b 1` to set the block time to 1s when using the `mini-net` command.

**How do we set the number of bakers?**
- In flextesa, we would set `--number-of-b 1` when using `mini-net` command.
- It looks like for TezBox we would add/remove bakers in `configuration/bakers.hjson`

**How do we generate implicit accounts?**
- With flextesa, we used to use `flextesa key jack` to generate an account.

**How do we preserve state/history?**
- In flextesa, we could set the root to a particular directory. Although we haven't implemented history, our thoughts was to try preserving the root.

Thanks again for your help and for putting this package together!

Cheers,
Mike

**Comment by cryi** [comment]
Hi @mweichert,

> How do we disable automatic baking?

There is no simple way ti disable baking entirely at this point. If you are ok with stopping it manually after container initialization you can run: 
```sh
docker exec -it <container id> asctl stop baker
```
Please let me know whether it is acceptable.

> How do we set the block time?

There is an example [in the readme](https://github.com/tez-capital/tezbox?tab=readme-ov-file#overrides-and-configuration-through-mounted-volumes). Basically you override sandbox parameters with your own value of block time. You can modify all protocol parameters this way.

> How do we set the number of bakers?

Yes adjusting content of the `bakers.hjson` is correct approach. But keep in mind that at least the `faucet` baker has to exist (but does NOT have to be baking). It is used to deposit accounts (from the `accounts.hjson`).

> How do we generate implicit accounts?

Depending on use case you can either mount your own `accounts.hjson` which takes care of setting up accounts or by hand as follows:

```sh
docker exec -it <container id> octez-client gen keys jack
docker exec -it <container id> octez-client show address jack
```

> How do we preserve state/history?

Tezbox is built with this in mind. All relevant data are stored in ` /tezbox/data` so just mount it to persistent storage and it should work out of box. (Please be aware that if you use rootless containers you may need to adjust folder permissions accordingly)

**Comment by cryi** [comment]
Hi @mweichert, it is possible to disable automatic start of services now. See [readme - configuration - services](https://github.com/tez-capital/tezbox?tab=readme-ov-file#services).

**Comment by mweichert** [comment]
@cryi sorry, somehow I missed the notification for this. We can close this. Thanks for all of your work on TezBox and giving Flextesa parity some attention.
