### ISSUE TITLE
not working docker image

### ISSUE THREAD

**Issue by serjonya-trili** [tez-capital/tezbox#9]
Hello,

The last update replaced the original tezos-v20.2 with the qena commit from yesterday.

Unfortunately, it doesn't work. On my mac M2 machine if I try to run the app using the commands from the README file it gives me this:

```
10:51:55 [INFO] (tezbox) generating node identity
rosetta error: failed to open elf at /lib/ld-musl-x86_64.so.1
 10:51:55 [ERROR] (tezbox) failed to generate node identity
eli: /usr/sbin/ascend:97: Failed to execute init script: exit
stack traceback:
	[C]: in function 'error'
	/usr/sbin/ascend:97: in upvalue 'run_init_hook'
	/usr/sbin/ascend:104: in function 'ascend.init.run'
	/usr/sbin/ascend:1872: in main chunk
	[C]: in ?
```
inside the container there is only ld-musl-aarch64.so.1, not the x86 one

so just for lulz I ran it like this:
```bash
docker run -it -p 0.0.0.0:8732:8732 --platform linux/amd64 ghcr.io/tez-capital/tezbox:tezos-v20.2 parisbox
```

the output is as follows:
```
10:50:26 [INFO] (tezbox) generating node identity
10:50:27 [ERROR] (tezbox) failed to generate node identity
eli: /usr/sbin/ascend:97: Failed to execute init script: exit
stack traceback:
	[C]: in function 'error'
	/usr/sbin/ascend:97: in upvalue 'run_init_hook'
	/usr/sbin/ascend:104: in function 'ascend.init.run'
	/usr/sbin/ascend:1872: in main chunk
	[C]: in ?
```

**Comment by cryi** [comment]
Hi @serjonya-trili, indeed I provided Qena binaries only for amd64 😞

**Comment by cryi** [comment]
Please try new image

**Comment by mweichert** [comment]
Hi @cryi , I'm having the same issue. If I start without specifying `qenabox` the sandbox starts, but the latest protocol is `PsParisCZo7KAh1Z1smVd9ZMZ1HHn5gkzbM94V3PLCpknFWhUAi`

I'm using `ghcr.io/tez-capital/tezbox:tezos-v20.3`  and `linux/amd64` platform.

**Comment by cryi** [comment]
@mweichert can you please confirm that image hash equals latest? (that there is not cached old version?)

**Comment by cryi** [comment]
Ok just noticed @mweichert that new images were not built after fix. Please try new image.

Also please check #5 . If it is all good we can close.

**Comment by mweichert** [comment]
@cryi still having issues on this end with `ghcr.io/tez-capital/tezbox:tezos-v20.3.20241003`

```
17:04:47 [ERROR] (tezbox) protocol qenabox not found in context
eli: /usr/sbin/ascend:97: Failed to execute init script: exit
stack traceback:
        [C]: in function 'error'
        /usr/sbin/ascend:97: in upvalue 'run_init_hook'
        /usr/sbin/ascend:104: in function 'ascend.init.run'
        /usr/sbin/ascend:1872: in main chunk
        [C]: in ?
```

**Comment by cryi** [comment]
Ah yea @mweichert qenabox wasn't really available until now with octez rc3. I will look into getting it out asap.

**Comment by cryi** [comment]
Please @mweichert see readme, there are new images with support for all Q protocols.

**Comment by serjonya-trili** [comment]
now it works, many thanks for fixing :)
